apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: angular-app
        image: awpindacr.azurecr.io/angular-app:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: REDIS
          value: "azure-vote-back"
      imagePullSecrets:
        - name: awppullsecret
---
apiVersion: v1
kind: Service
metadata:
  name: angular-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: angular-app
